# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
